//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamMerge {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamMerge.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable auto select all changesets..
        /// </summary>
        public static string AutoSelectAllChangesets {
            get {
                return ResourceManager.GetString("AutoSelectAllChangesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for included pending changes.
        /// </summary>
        public static string CheckingPendingChanges {
            get {
                return ResourceManager.GetString("CheckingPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch changesets.
        /// </summary>
        public static string FetchChangesets {
            get {
                return ResourceManager.GetString("FetchChangesets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflicts occurred when getting latest. Open the conflict window to resolve these issues..
        /// </summary>
        public static string GetLatestConflicts {
            get {
                return ResourceManager.GetString("GetLatestConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest version for {0} branch..
        /// </summary>
        public static string GettingLatestVersionForBranch {
            get {
                return ResourceManager.GetString("GettingLatestVersionForBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before merging do get latest version on branch:.
        /// </summary>
        public static string LatestVersionBranch {
            get {
                return ResourceManager.GetString("LatestVersionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging branches.
        /// </summary>
        public static string MergingBranches {
            get {
                return ResourceManager.GetString("MergingBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NotSelected).
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name:.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to save your changes?.
        /// </summary>
        public static string SaveYourChanges {
            get {
                return ResourceManager.GetString("SaveYourChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should resolve conflicts.
        /// </summary>
        public static string ShouldResolveConflicts {
            get {
                return ResourceManager.GetString("ShouldResolveConflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soure and target.
        /// </summary>
        public static string SourceAndTarget {
            get {
                return ResourceManager.GetString("SourceAndTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source branch.
        /// </summary>
        public static string SourceBranch {
            get {
                return ResourceManager.GetString("SourceBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target branch.
        /// </summary>
        public static string TargetBranch {
            get {
                return ResourceManager.GetString("TargetBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Merge.
        /// </summary>
        public static string TeamMerge {
            get {
                return ResourceManager.GetString("TeamMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamMerge settings.
        /// </summary>
        public static string TeamMergeSettings {
            get {
                return ResourceManager.GetString("TeamMergeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable warning when merging with included pending changes in workspace..
        /// </summary>
        public static string WarningPendingChanges {
            get {
                return ResourceManager.GetString("WarningPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your workspace contains included pending changes. Exclude or undo your included pending changes before merging..
        /// </summary>
        public static string WorkspaceContainsPendingChanges {
            get {
                return ResourceManager.GetString("WorkspaceContainsPendingChanges", resourceCulture);
            }
        }
    }
}
